### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Rayeliint** [Mattat01/ha-insnrg-chlorinator#1]
Hi there.
First off, great work on this. Shame INSNRG didnt act on it.

I have installed the files and added the integration but get an error
``
Config flow could not be loaded: {"message":"Invalid handler specified"}
``
Any ideas on this please?

**Comment by Rayeliint** [comment]
Actually, just tried again and it has installed now.
I comes up with another error now!
![Screenshot 2024-10-19 at 8 50 59 AM](https://github.com/user-attachments/assets/54404cec-6339-429e-bcf2-982516252922)

**Comment by Mattat01** [comment]
Oooo, how exciting, a mystery!

I agree on INSNRG, I love they are local and made something connected, but disapointed they never released an API. I spoke to the owner when I got mine (he helped install and set it up a very long time ago), and he said they planned to, but had concerns about getting API calls on high repeat (and I guess the minimal server cost that might incur). Anyway, that's why I set it to poll once an hour.

Ah, just got your message whilst looking at it. I have the datetime issue too. I didn't spot it because it was a very tiny change I made at 2am and it seemed to work... I'll have it fixed in a few minutes, hopefully.

**Comment by Mattat01** [comment]
Ok, try updating the coordinator.py file and restarting HA. It is working in mine now. Strangely it says my pH is 6484.4, but so it the official portal, so who am I to tell them they are wrong (better not swim today)... Let me know how you go this time.

**Comment by Mattat01** [comment]
Sorry, forgot to push the change. the correct version has a commit  message "fixed datetime issue caused when HA stores datetime as a string"

**Comment by Rayeliint** [comment]
Great work, all up and running now.
One thing I would really like is the temperature. Being an old bugger, need to know before I hop in!!
Also have lights connected to the system and would be good to at least turn these on and off.
Any help I can give in my small capacity?

**Comment by Mattat01** [comment]
Excellent. Glad it worked (Phew)

I don't have temperature or lights connected to mine, but we can probably fudge something... I'll send you a DM through the HA forum to ask for the info I expect I'd need. Let me know if (when) I break something else!

Thanks.

**Comment by Rayeliint** [comment]
> Excellent. Glad it worked (Phew)
> 
> I don't have temperature or lights connected to mine, but we can probably fudge something... I'll send you a DM through the HA forum to ask for the info I expect I'd need. Let me know if (when) I break something else!
> 
> Thanks.

Great, thank you
